#!/bin/sh
ENABLED="yes"
WORK_DIR="/opt/etc/AdGuardHome"
PID_FILE="/opt/var/run/AdGuardHome.pid"
PROCS="AdGuardHome"
ARGS="-s run -c ${WORK_DIR}/AdGuardHome.yaml -w $WORK_DIR --pidfile $PID_FILE --no-check-update -l syslog"
PREARGS="env TZ=/etc/localtime GOGC=40 GOMEMLIMIT=64MiB"
PRECMD="unlimit -s 64; until pidof $PROCS | grep -qE '.*'; do { killall -9 $(netstat -nlp 2>/dev/null | awk -F/ -v VAR='$PROCS' '$0 ~ /.*:53[[:space:]].*/ && $0 !~ VAR {if(!x[$2]++) printf "%s ", $2}') || kill -s 9 $(netstat -nlp 2>/dev/null | awk -v VAR='$PROCS' '$0 ~ /.*:53[[:space:]].*/ && $0 !~ VAR {match($7, /[0-9]+/); if (RSTART && !x[$7]++) printf "%s ", substr($7, RSTART, RLENGTH)}'); }; service stop_dnsmasq; done &"
POSTCMD="service restart_dnsmasq"
DESC="$PROCS"
PATH="/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export TZ="$(cat /etc/TZ)"
[ -z "$SCRIPT_LOC" ] && . /jffs/addons/AdGuardHome.d/AdGuardHome.sh
