sonar.projectKey=jumpsmm7_Asuswrt-Merlin-AdGuardHome-Installer
sonar.organization=your-sonarcloud-org-key
sonar.sources=.jumpsmm7
sonar.exclusions=**/test/**,**/node_modules/**,**/.*
sonar.shell.file.suffixes=.sh
