#!/bin/sh
# Regression test for the qodo-pr-resolver skill's cross-document convergence
# contract. The oscillation guard (Step 3c / convergence.md) only works if the
# round-detection marker and heading are stated identically, byte-for-byte,
# across every document that describes how to read or write them. A future
# edit that tweaks the wording, punctuation, or dash character in only one
# copy would silently break round detection for that provider without any
# other signal.

set -u

SKILL='.agents/skills/qodo-pr-resolver/SKILL.md'
CONVERGENCE='.agents/skills/qodo-pr-resolver/resources/convergence.md'
GERRIT='.agents/skills/qodo-pr-resolver/resources/gerrit.md'
PROVIDERS='.agents/skills/qodo-pr-resolver/resources/providers.md'

fail() {
	printf '%s\n' "FAIL: $1" >&2
	exit 1
}

for f in "${SKILL}" "${CONVERGENCE}" "${GERRIT}" "${PROVIDERS}"; do
	[ -f "${f}" ] || fail "expected qodo-pr-resolver doc not found: ${f}"
done

# --- The round-of-record marker must appear verbatim in every document that
# either produces it (SKILL.md, providers.md) or consumes it (SKILL.md,
# convergence.md, gerrit.md).
MARKER='Generated by Qodo PR Resolver skill'
for f in "${SKILL}" "${CONVERGENCE}" "${GERRIT}" "${PROVIDERS}"; do
	grep -Fq "${MARKER}" "${f}" || fail "${f}: missing the round-of-record marker '${MARKER}'"
done

# --- The fix-summary heading format (including the exact em dash) must also
# be byte-identical everywhere it is referenced, since round-number parsing
# depends on matching this literal string.
HEADING='Qodo Fix Summary — Round N'
for f in "${SKILL}" "${CONVERGENCE}" "${GERRIT}" "${PROVIDERS}"; do
	grep -Fq "${HEADING}" "${f}" || fail "${f}: missing the exact fix-summary heading '${HEADING}'"
done

# --- providers.md must contain the literal heading as it would actually be
# posted (not just referenced in prose elsewhere), since it is the canonical
# summary-format example other docs point back to.
grep -Fq '## Qodo Fix Summary — Round N' "${PROVIDERS}" ||
	fail "${PROVIDERS}: expected the literal posted heading '## Qodo Fix Summary — Round N'"

# --- The ledger's primary lookup key (file + title, never raw line number) is
# the crux of the oscillation guard; it must be stated consistently in both
# SKILL.md and convergence.md so a future edit can't silently key on line
# number alone and reintroduce the flip-flop bug the guard exists to prevent.
for f in "${SKILL}" "${CONVERGENCE}"; do
	grep -Fq '`file` + `title`' "${f}" || fail "${f}: expected the ledger key description to mention the complete '\`file\` + \`title\`' key"
done

# --- The hard-stop threshold (>=2 flips triggers a refusal on the 3rd cycle)
# must agree between SKILL.md and convergence.md; a drift here would either
# make the guard too permissive (allowing more oscillation than documented)
# or too strict (blocking legitimate fixes prematurely).
grep -Fq '2 flips' "${CONVERGENCE}" || fail "${CONVERGENCE}: expected the hard-stop threshold to reference '2 flips'"
grep -Fq '3rd oscillation cycle' "${SKILL}" || fail "${SKILL}: expected the hard-stop description to reference the '3rd oscillation cycle'"

# --- Sanity check on the marker/heading fixtures themselves: guard against a
# future edit accidentally weakening this test by narrowing the constants to
# an empty or trivially-matching string.
[ -n "${MARKER}" ] || fail 'internal test error: MARKER constant is empty'
[ -n "${HEADING}" ] || fail 'internal test error: HEADING constant is empty'

printf '%s\n' 'PASS: qodo-pr-resolver docs keep the round-of-record marker, heading, and oscillation-guard contract consistent'
