#!/bin/sh
# Regression test for the qodo-pr-resolver skill's cross-document convergence
# contract. The oscillation guard (Step 3c / convergence.md) only works if the
# round-detection marker and heading are stated identically, byte-for-byte,
# across every document that describes how to read or write them. A future
# edit that tweaks the wording, punctuation, or dash character in only one
# copy would silently break round detection for that provider without any
# other signal.

set -u

SKILL='.agents/skills/qodo-pr-resolver/SKILL.md'
CONVERGENCE='.agents/skills/qodo-pr-resolver/resources/convergence.md'
GERRIT='.agents/skills/qodo-pr-resolver/resources/gerrit.md'
PROVIDERS='.agents/skills/qodo-pr-resolver/resources/providers.md'

# fail prints a failure message to stderr and exits with status 1.
fail() {
	printf '%s\n' "FAIL: $1" >&2
	exit 1
}

for f in "${SKILL}" "${CONVERGENCE}" "${GERRIT}" "${PROVIDERS}"; do
	[ -f "${f}" ] || fail "expected qodo-pr-resolver doc not found: ${f}"
done

# --- The round-of-record marker must appear verbatim in every document that
# either produces it (SKILL.md, providers.md) or consumes it (SKILL.md,
# convergence.md, gerrit.md).
MARKER='Generated by Qodo PR Resolver skill'
for f in "${SKILL}" "${CONVERGENCE}" "${GERRIT}" "${PROVIDERS}"; do
	grep -Fq "${MARKER}" "${f}" || fail "${f}: missing the round-of-record marker '${MARKER}'"
done

# --- The fix-summary heading format (including the exact em dash) must also
# be byte-identical everywhere it is referenced, since round-number parsing
# depends on matching this literal string.
HEADING='Qodo Fix Summary — Round N'
for f in "${SKILL}" "${CONVERGENCE}" "${GERRIT}" "${PROVIDERS}"; do
	grep -Fq "${HEADING}" "${f}" || fail "${f}: missing the exact fix-summary heading '${HEADING}'"
done

# --- providers.md must contain the literal heading as it would actually be
# posted (not just referenced in prose elsewhere), since it is the canonical
# summary-format example other docs point back to.
grep -Fq '## Qodo Fix Summary — Round N' "${PROVIDERS}" ||
	fail "${PROVIDERS}: expected the literal posted heading '## Qodo Fix Summary — Round N'"

# --- Dynamic summaries contain verbatim issue titles and user-provided
# reasons. Keep both CLI examples on file-based input so apostrophes and shell
# operators in that untrusted text are never parsed as part of a command.
grep -Fq 'gh pr comment <pr-number> --body-file "$COMMENT_FILE"' "${PROVIDERS}" ||
	fail "${PROVIDERS}: GitHub summaries must use --body-file"
grep -Fq 'glab mr comment <mr-iid> < "$COMMENT_FILE"' "${PROVIDERS}" ||
	fail "${PROVIDERS}: GitLab summaries must read the body from a file"
if grep -Fq "gh pr comment <pr-number> --body '<comment-body>'" "${PROVIDERS}"; then
	fail "${PROVIDERS}: unsafe shell-quoted GitHub summary example is present"
fi
if grep -Fq "glab mr comment <mr-iid> --message '<comment-body>'" "${PROVIDERS}"; then
	fail "${PROVIDERS}: unsafe shell-quoted GitLab summary example is present"
fi

# --- Generic validation: scan every gh/glab summary-posting command in one
# pass. Remove only safe input for the specific body/description flag, then
# reject any remaining inline --body/--message/--description argument. This
# keeps a safe title (or another safe flag) from masking an unsafe body on the
# same command and covers single-quoted, double-quoted, and unquoted values.
UNSAFE_COMMANDS=$(mktemp "${TMPDIR:-/tmp}/unsafe_commands.XXXXXX") || exit 1
trap 'rm -f "$UNSAFE_COMMANDS"' 0

scan_unsafe_commands() {
	awk '
	function inspect_command(command, sanitized) {
		if (command !~ /(gh pr (comment|create)|glab mr (comment|note|create))/)
			return
		sanitized = command
		gsub(/--body-file[[:space:]]+[^[:space:]]+/, "", sanitized)
		gsub(/--(body|message|description)([[:space:]]+|=)"\$\(cat[[:space:]]+"\$[A-Za-z_][A-Za-z0-9_]*"\)"/, "", sanitized)
		if (sanitized ~ /--(body|message|description)([[:space:]]|=)/)
			print command
	}
	{
		line = $0
		if (command != "")
			sub(/^[[:space:]]+/, "", line)
		command = command (command == "" ? "" : " ") line
		if (command ~ /\\[[:space:]]*$/) {
			sub(/[[:space:]]*\\[[:space:]]*$/, "", command)
			next
		}
		inspect_command(command)
		command = ""
	}
	END {
		if (command != "")
			inspect_command(command)
	}
	' "$1"
}

# Exercise every accepted input path and the quoting/argument variants that
# previously bypassed this guard. These fixtures keep the scanner itself from
# silently regressing when providers.md happens not to contain an unsafe line.
scan_unsafe_commands - >"${UNSAFE_COMMANDS}" <<'EOF'
gh pr comment 1 --body-file "$COMMENT_FILE" # safe-body-file
glab mr comment 1 < "$COMMENT_FILE" # safe-stdin
gh pr create --body "$(cat "$BODY_FILE")" # safe-cat-space
gh pr create --body="$(cat "$BODY_FILE")" # safe-cat-equals
gh pr create --title "$(cat "$TITLE_FILE")" --body "$BODY" # unsafe-mixed-title
gh pr comment 1 --body '$BODY' # unsafe-single-quote
glab mr note 1 --message "$MESSAGE" # unsafe-double-quote
glab mr create --description=$DESCRIPTION # unsafe-unquoted
glab mr create \
  --description "$MULTILINE_DESCRIPTION" # unsafe-continuation
gh pr create --body-file "$BODY_FILE" --description "$DESCRIPTION" # unsafe-mixed-body-file
EOF

EXPECTED_UNSAFE='gh pr create --title "$(cat "$TITLE_FILE")" --body "$BODY" # unsafe-mixed-title
gh pr comment 1 --body '\''$BODY'\'' # unsafe-single-quote
glab mr note 1 --message "$MESSAGE" # unsafe-double-quote
glab mr create --description=$DESCRIPTION # unsafe-unquoted
glab mr create --description "$MULTILINE_DESCRIPTION" # unsafe-continuation
gh pr create --body-file "$BODY_FILE" --description "$DESCRIPTION" # unsafe-mixed-body-file'
[ "$(cat "${UNSAFE_COMMANDS}")" = "${EXPECTED_UNSAFE}" ] ||
	fail 'internal test error: unsafe command scanner did not classify all regression fixtures correctly'

scan_unsafe_commands "${PROVIDERS}" >"${UNSAFE_COMMANDS}"

if [ -s "$UNSAFE_COMMANDS" ]; then
	cmd=$(head -n 1 "$UNSAFE_COMMANDS" | sed 's/^[[:space:]]*//')
	rm -f "$UNSAFE_COMMANDS"
	fail "${PROVIDERS}: found potentially unsafe inline body in command: $cmd"
fi
rm -f "$UNSAFE_COMMANDS"

# --- The ledger's primary lookup key (file + title, never raw line number) is
# the crux of the oscillation guard; it must be stated consistently in both
# SKILL.md and convergence.md so a future edit can't silently key on line
# number alone and reintroduce the flip-flop bug the guard exists to prevent.
for f in "${SKILL}" "${CONVERGENCE}"; do
	grep -Fq '`file` + `title`' "${f}" || fail "${f}: expected the ledger key description to mention the complete '\`file\` + \`title\`' key"
done

# --- The hard-stop threshold (>=2 flips triggers a refusal on the 3rd cycle)
# must agree between SKILL.md and convergence.md; a drift here would either
# make the guard too permissive (allowing more oscillation than documented)
# or too strict (blocking legitimate fixes prematurely).
grep -Fq '2 flips' "${CONVERGENCE}" || fail "${CONVERGENCE}: expected the hard-stop threshold to reference '2 flips'"
grep -Fq '3rd oscillation cycle' "${SKILL}" || fail "${SKILL}: expected the hard-stop description to reference the '3rd oscillation cycle'"

# --- Sanity check on the marker/heading fixtures themselves: guard against a
# future edit accidentally weakening this test by narrowing the constants to
# an empty or trivially-matching string.
[ -n "${MARKER}" ] || fail 'internal test error: MARKER constant is empty'
[ -n "${HEADING}" ] || fail 'internal test error: HEADING constant is empty'

printf '%s\n' 'PASS: qodo-pr-resolver docs keep the round-of-record marker, heading, and oscillation-guard contract consistent'
