#!/bin/sh
# Download static AdGuardHome release archives for router architectures.
# BusyBox/ash-compatible. Avoid Bash-only syntax.

set -u

BASE_URL="https://static.adguard.com/adguardhome"
OUT_DIR="${1:-.}"
FAILED=0

# Functions are sorted alpha-numerically for readability.

append_metadata() {
	_folder="$1"
	_channel_name="$2"
	_remote_channel="$3"
	_adguard_arch="$4"
	_archive_file="$5"
	_version="$6"
	_md5="$7"
	_sha256="$8"
	_dest_dir="${OUT_DIR}/${_folder}"

	printf '%s\t%s\t%s\t%s\n' "${_archive_file}" "${_channel_name}" "${_remote_channel}" "${_version}" >>"${_dest_dir}/VERSION.txt.tmp" &&
		printf '%s\t%s\t%s\t%s\t%s\n' "${_archive_file}" "${_channel_name}" "${_version}" "${_md5}" "${_sha256}" >>"${_dest_dir}/checksum.txt.tmp"
}

calc_sum() {
	_sum_cmd="$1"
	_file="$2"
	_sum_output=""

	_sum_output="$("${_sum_cmd}" "${_file}")" || return 1
	printf '%s\n' "${_sum_output}" | awk 'NF {print $1; found = 1; exit} END {if (!found) exit 1}'
}

download_arch() {
	_folder="$1"
	_adguard_arch="$2"
	_dest_dir="${OUT_DIR}/${_folder}"

	mkdir -p "${_dest_dir}" || {
		printf '%s\n' "Error: could not create ${_dest_dir}" >&2
		FAILED=1
		return 1
	}

	{
		printf '%s\n' '# Generated by tools/download-adguardhome-static.sh'
		printf '%s\n' '# file	channel	upstream_channel	version'
	} >"${_dest_dir}/VERSION.txt.tmp" || {
		printf '%s\n' "Error: could not initialize ${_dest_dir}/VERSION.txt.tmp" >&2
		FAILED=1
		return 1
	}
	{
		printf '%s\n' '# Generated by tools/download-adguardhome-static.sh'
		printf '%s\n' '# file	channel	version	md5	sha256'
	} >"${_dest_dir}/checksum.txt.tmp" || {
		rm -f "${_dest_dir}/VERSION.txt.tmp"
		printf '%s\n' "Error: could not initialize ${_dest_dir}/checksum.txt.tmp" >&2
		FAILED=1
		return 1
	}

	download_one "${_folder}" stable release "${_adguard_arch}" || true
	download_one "${_folder}" beta beta "${_adguard_arch}" || true
	download_one "${_folder}" edge edge "${_adguard_arch}" || true

	if ! chmod 644 "${_dest_dir}/VERSION.txt.tmp" "${_dest_dir}/checksum.txt.tmp"; then
		rm -f "${_dest_dir}/VERSION.txt.tmp" "${_dest_dir}/checksum.txt.tmp"
		printf '%s\n' "Error: could not set metadata permissions for ${_folder}" >&2
		FAILED=1
		return 1
	fi
	publish_metadata_files "${_dest_dir}" || return 1
}

download_one() {
	_folder="$1"
	_channel_name="$2"
	_remote_channel="$3"
	_adguard_arch="$4"
	_adguard_tar="AdGuardHome_${_adguard_arch}.tar.gz"
	_url="${BASE_URL}/${_remote_channel}/${_adguard_tar}"
	_version_url="${BASE_URL}/${_remote_channel}/version.txt"
	_dest_dir="${OUT_DIR}/${_folder}"
	_dest_file="${_dest_dir}/AdGuardHome_${_channel_name}_${_adguard_arch}.tar.gz"
	_dest_name="${_dest_file##*/}"
	_tmp_file="${_dest_file}.tmp.$$"
	_version=""
	_md5=""
	_sha256=""

	printf '%s\n' "Downloading ${_version_url}"
	_version_response="$(curl -fsL --retry 3 --retry-delay 5 --connect-timeout 30 --max-time 120 "${_version_url}")" || {
		printf '%s\n' "Error: failed to download ${_version_url}" >&2
		FAILED=1
		return 1
	}
	_version="$(printf '%s\n' "${_version_response}" | awk 'NF {print $1; found = 1; exit} END {if (!found) exit 1}')" || {
		printf '%s\n' "Error: invalid version metadata from ${_version_url}" >&2
		FAILED=1
		return 1
	}
	if [ -z "${_version}" ]; then
		printf '%s\n' "Error: empty version metadata from ${_version_url}" >&2
		FAILED=1
		return 1
	fi

	printf '%s\n' "Downloading ${_url} -> ${_dest_file}"
	if ! curl -fL --retry 3 --retry-delay 5 --connect-timeout 30 --max-time 600 -o "${_tmp_file}" "${_url}"; then
		rm -f "${_tmp_file}"
		printf '%s\n' "Error: failed to download ${_url}" >&2
		FAILED=1
		return 1
	fi

	if ! gzip -t "${_tmp_file}"; then
		rm -f "${_tmp_file}"
		printf '%s\n' "Error: downloaded archive is not a valid gzip file: ${_url}" >&2
		FAILED=1
		return 1
	fi

	_md5="$(calc_sum md5sum "${_tmp_file}")" || {
		rm -f "${_tmp_file}"
		printf '%s\n' "Error: failed to calculate md5 for ${_url}" >&2
		FAILED=1
		return 1
	}
	_sha256="$(calc_sum sha256sum "${_tmp_file}")" || {
		rm -f "${_tmp_file}"
		printf '%s\n' "Error: failed to calculate sha256 for ${_url}" >&2
		FAILED=1
		return 1
	}

	if [ -f "${_dest_file}" ] && cmp -s "${_tmp_file}" "${_dest_file}"; then
		rm -f "${_tmp_file}"
		printf '%s\n' "OK: ${_dest_file} already current"
		write_md5sum_file "${_dest_file}" "${_md5}" || return 1
	else
		publish_archive_with_md5 "${_tmp_file}" "${_dest_file}" "${_md5}" || return 1
		printf '%s\n' "Updated ${_dest_file}"
	fi

	if ! append_metadata "${_folder}" "${_channel_name}" "${_remote_channel}" "${_adguard_arch}" "${_dest_name}" "${_version}" "${_md5}" "${_sha256}"; then
		printf '%s\n' "Error: could not append metadata for ${_dest_name}" >&2
		FAILED=1
		return 1
	fi
}

publish_archive_with_md5() {
	_archive_tmp="$1"
	_archive_file="$2"
	_md5="$3"
	_md5_file="${_archive_file}.md5sum"
	_md5_tmp="${_md5_file}.tmp.$$"
	_archive_backup="${_archive_file}.previous.$$"
	_md5_backup="${_md5_file}.previous.$$"
	_had_archive=0
	_had_md5=0
	_restore_failed=0

	rm -f "${_archive_backup}" "${_md5_backup}" "${_md5_tmp}"
	if ! printf '%s\n' "${_md5}" >"${_md5_tmp}" ||
		! chmod 644 "${_archive_tmp}" "${_md5_tmp}"; then
		rm -f "${_archive_tmp}" "${_md5_tmp}"
		printf '%s\n' "Error: could not prepare ${_archive_file}" >&2
		FAILED=1
		return 1
	fi

	if [ -f "${_archive_file}" ]; then
		_had_archive=1
		if ! cp -p "${_archive_file}" "${_archive_backup}"; then
			rm -f "${_archive_tmp}" "${_md5_tmp}"
			printf '%s\n' "Error: could not preserve ${_archive_file}" >&2
			FAILED=1
			return 1
		fi
	fi
	if [ -f "${_md5_file}" ]; then
		_had_md5=1
		if ! cp -p "${_md5_file}" "${_md5_backup}"; then
			rm -f "${_archive_backup}" "${_archive_tmp}" "${_md5_tmp}"
			printf '%s\n' "Error: could not preserve ${_md5_file}" >&2
			FAILED=1
			return 1
		fi
	fi

	if mv "${_archive_tmp}" "${_archive_file}" &&
		mv "${_md5_tmp}" "${_md5_file}"; then
		rm -f "${_archive_backup}" "${_md5_backup}"
		return 0
	fi

	rm -f "${_archive_file}" "${_md5_file}" "${_archive_tmp}" "${_md5_tmp}"
	if [ "${_had_archive}" -eq 1 ]; then
		mv "${_archive_backup}" "${_archive_file}" || _restore_failed=1
	fi
	if [ "${_had_md5}" -eq 1 ]; then
		mv "${_md5_backup}" "${_md5_file}" || _restore_failed=1
	fi
	printf '%s\n' "Error: could not publish ${_archive_file} and its checksum" >&2
	if [ "${_restore_failed}" -ne 0 ]; then
		printf '%s\n' "Error: recovery failed; inspect ${_archive_backup} and ${_md5_backup}" >&2
	fi
	FAILED=1
	return 1
}

publish_metadata_files() {
	_dest_dir="$1"
	_version_file="${_dest_dir}/VERSION.txt"
	_checksum_file="${_dest_dir}/checksum.txt"
	_version_tmp="${_version_file}.tmp"
	_checksum_tmp="${_checksum_file}.tmp"
	_version_backup="${_version_file}.previous.$$"
	_checksum_backup="${_checksum_file}.previous.$$"
	_had_version=0
	_had_checksum=0
	_restore_failed=0

	rm -f "${_version_backup}" "${_checksum_backup}"
	if [ -f "${_version_file}" ]; then
		_had_version=1
		if ! mv "${_version_file}" "${_version_backup}"; then
			rm -f "${_version_tmp}" "${_checksum_tmp}"
			printf '%s\n' "Error: could not preserve ${_version_file}" >&2
			FAILED=1
			return 1
		fi
	fi
	if [ -f "${_checksum_file}" ]; then
		_had_checksum=1
		if ! mv "${_checksum_file}" "${_checksum_backup}"; then
			if [ "${_had_version}" -eq 1 ]; then
				mv "${_version_backup}" "${_version_file}" || _restore_failed=1
			fi
			rm -f "${_version_tmp}" "${_checksum_tmp}"
			printf '%s\n' "Error: could not preserve ${_checksum_file}" >&2
			[ "${_restore_failed}" -eq 0 ] ||
				printf '%s\n' "Error: previous metadata remains at ${_version_backup}" >&2
			FAILED=1
			return 1
		fi
	fi

	if mv "${_version_tmp}" "${_version_file}" &&
		mv "${_checksum_tmp}" "${_checksum_file}"; then
		rm -f "${_version_backup}" "${_checksum_backup}"
		return 0
	fi

	rm -f "${_version_file}" "${_checksum_file}" "${_version_tmp}" "${_checksum_tmp}"
	if [ "${_had_version}" -eq 1 ]; then
		mv "${_version_backup}" "${_version_file}" || _restore_failed=1
	fi
	if [ "${_had_checksum}" -eq 1 ]; then
		mv "${_checksum_backup}" "${_checksum_file}" || _restore_failed=1
	fi
	printf '%s\n' "Error: could not publish metadata for ${_dest_dir}" >&2
	if [ "${_restore_failed}" -ne 0 ]; then
		printf '%s\n' "Error: metadata recovery failed; inspect ${_version_backup} and ${_checksum_backup}" >&2
	fi
	FAILED=1
	return 1
}

require_cmd() {
	_cmd="$1"
	if which "${_cmd}" >/dev/null 2>&1; then
		return 0
	fi

	printf '%s\n' "Error: ${_cmd} is required." >&2
	exit 1
}

write_md5sum_file() {
	_archive_file="$1"
	_md5="$2"
	_md5_file="${_archive_file}.md5sum"
	_md5_tmp="${_md5_file}.tmp.$$"

	if ! printf '%s\n' "${_md5}" >"${_md5_tmp}" || ! chmod 644 "${_md5_tmp}" || ! mv "${_md5_tmp}" "${_md5_file}"; then
		rm -f "${_md5_tmp}"
		printf '%s\n' "Error: could not update ${_md5_file}" >&2
		FAILED=1
		return 1
	fi
}

require_cmd awk
require_cmd curl
require_cmd gzip
require_cmd md5sum
require_cmd sha256sum

download_arch armv8 linux_arm64
download_arch armv7 linux_armv7
download_arch armv5 linux_armv5

if [ "${FAILED}" -ne 0 ]; then
	exit 1
fi
