#!/bin/sh
# Download static AdGuardHome release archives for router architectures.
# BusyBox/ash-compatible. Avoid Bash-only syntax.

set -u

BASE_URL="https://static.adguard.com/adguardhome"
OUT_DIR="${1:-.}"
FAILED=0
ACTIVE_DOWNLOAD_TMP=""
ACTIVE_PUBLICATION_ARCHIVE=""

# Functions are sorted alpha-numerically for readability.

cleanup_download_tmp() {
	if [ -n "${ACTIVE_PUBLICATION_ARCHIVE:-}" ]; then
		if ! recover_archive_publication "${ACTIVE_PUBLICATION_ARCHIVE}" "$$"; then
			printf '%s\n' "Error: recovery failed for ${ACTIVE_PUBLICATION_ARCHIVE}" >&2
		fi
		ACTIVE_PUBLICATION_ARCHIVE=""
	fi
	if [ -n "${ACTIVE_DOWNLOAD_TMP:-}" ]; then
		rm -f "${ACTIVE_DOWNLOAD_TMP}"
		ACTIVE_DOWNLOAD_TMP=""
	fi
}

append_metadata() {
	_folder="$1"
	_channel_name="$2"
	_remote_channel="$3"
	_adguard_arch="$4"
	_archive_file="$5"
	_version="$6"
	_md5="$7"
	_sha256="$8"
	_dest_dir="${OUT_DIR}/${_folder}"

	printf '%s\t%s\t%s\t%s\n' "${_archive_file}" "${_channel_name}" "${_remote_channel}" "${_version}" >>"${_dest_dir}/VERSION.txt.tmp" &&
		printf '%s\t%s\t%s\t%s\t%s\n' "${_archive_file}" "${_channel_name}" "${_version}" "${_md5}" "${_sha256}" >>"${_dest_dir}/checksum.txt.tmp"
}

acquire_metadata_publication_lock() {
	_dest_dir="$1"
	_lock_file="${_dest_dir}/.metadata.lock"
	_lock_tmp="${_lock_file}.$$"
	_publish_start_time=""

	_publish_start_time="$(awk '{
		sub(/^.*\) /, "")
		print $20
	}' "/proc/$$/stat" 2>/dev/null)" || _publish_start_time=""
	case "${_publish_start_time}" in
		"" | *[!0-9]*)
			printf '%s\n' "Error: could not identify metadata lock owner for ${_dest_dir}" >&2
			FAILED=1
			return 1
			;;
	esac
	if ! printf '%s %s\n' "$$" "${_publish_start_time}" >"${_lock_tmp}"; then
		printf '%s\n' "Error: could not prepare metadata lock owner for ${_dest_dir}" >&2
		FAILED=1
		return 1
	fi

	while ! ln "${_lock_tmp}" "${_lock_file}" 2>/dev/null; do
		if [ -d "${_lock_file}" ]; then
			_legacy_owner="${_lock_file}/owner"
			if [ -f "${_legacy_owner}" ] &&
				archive_publication_owner_is_active "${_legacy_owner}"; then
				rm -f "${_lock_tmp}"
				printf '%s\n' "Error: metadata generation is already in progress for ${_dest_dir}" >&2
				FAILED=1
				return 1
			fi
			rm -f "${_legacy_owner}"
			rmdir "${_lock_file}" 2>/dev/null || {
				rm -f "${_lock_tmp}"
				printf '%s\n' "Error: metadata generation is already in progress for ${_dest_dir}" >&2
				FAILED=1
				return 1
			}
			continue
		fi
		if [ -f "${_lock_file}" ] &&
			archive_publication_owner_is_active "${_lock_file}"; then
			rm -f "${_lock_tmp}"
			printf '%s\n' "Error: metadata generation is already in progress for ${_dest_dir}" >&2
			FAILED=1
			return 1
		fi
		if ! reclaim_stale_metadata_publication_lock "${_lock_file}"; then
			rm -f "${_lock_tmp}"
			printf '%s\n' "Error: metadata generation is already in progress for ${_dest_dir}" >&2
			FAILED=1
			return 1
		fi
	done
	rm -f "${_lock_tmp}"
}

reclaim_stale_metadata_publication_lock() {
	_lock_file="$1"
	_stale_candidate="${_lock_file}.stale.$$"

	rm -f "${_stale_candidate}" 2>/dev/null
	ln "${_lock_file}" "${_stale_candidate}" 2>/dev/null || return 1
	if archive_publication_owner_is_active "${_stale_candidate}"; then
		rm -f "${_stale_candidate}"
		return 1
	fi
	_lock_identity="$(stat -c '%d:%i' "${_lock_file}" 2>/dev/null)" || {
		rm -f "${_stale_candidate}"
		return 1
	}
	_stale_identity="$(stat -c '%d:%i' "${_stale_candidate}" 2>/dev/null)" || {
		rm -f "${_stale_candidate}"
		return 1
	}
	if [ "${_lock_identity}" != "${_stale_identity}" ]; then
		rm -f "${_stale_candidate}"
		return 1
	fi
	rm -f "${_lock_file}" 2>/dev/null || {
		rm -f "${_stale_candidate}"
		return 1
	}
	rm -f "${_stale_candidate}"
}

# calc_sum computes and prints the hexadecimal checksum for a file using the specified checksum command.
calc_sum() {
	_sum_cmd="$1"
	_file="$2"
	_sum_output=""

	_sum_output="$("${_sum_cmd}" "${_file}")" || return 1
	_sum_value="$(printf '%s\n' "${_sum_output}" | awk 'NF {print $1; found = 1; exit} END {if (!found) exit 1}')" || return 1
	case "${_sum_cmd}:${_sum_value}" in
		md5sum:???????????????????????????????? | sha256sum:????????????????????????????????????????????????????????????????) ;;
		*) return 1 ;;
	esac
	case "${_sum_value}" in
		*[!0123456789abcdefABCDEF]*) return 1 ;;
	esac
	printf '%s\n' "${_sum_value}"
}

# download_arch downloads releases for an architecture, publishes channel metadata, and removes obsolete archives.
# The folder identifies the output directory, and the architecture identifies the upstream release variant.
download_arch() {
	_folder="$1"
	_adguard_arch="$2"
	_dest_dir="${OUT_DIR}/${_folder}"

	mkdir -p "${_dest_dir}" || {
		printf '%s\n' "Error: could not create ${_dest_dir}" >&2
		FAILED=1
		return 1
	}
	acquire_metadata_publication_lock "${_dest_dir}" || return 1
	recover_metadata_publication "${_dest_dir}" || {
		release_metadata_publication_lock "${_dest_dir}"
		return 1
	}

	{
		printf '%s\n' '# Generated by tools/download-adguardhome-static.sh'
		printf '%s\n' '# file	channel	upstream_channel	version'
	} >"${_dest_dir}/VERSION.txt.tmp" || {
		printf '%s\n' "Error: could not initialize ${_dest_dir}/VERSION.txt.tmp" >&2
		FAILED=1
		release_metadata_publication_lock "${_dest_dir}"
		return 1
	}
	{
		printf '%s\n' '# Generated by tools/download-adguardhome-static.sh'
		printf '%s\n' '# file	channel	version	md5	sha256'
	} >"${_dest_dir}/checksum.txt.tmp" || {
		rm -f "${_dest_dir}/VERSION.txt.tmp"
		printf '%s\n' "Error: could not initialize ${_dest_dir}/checksum.txt.tmp" >&2
		FAILED=1
		release_metadata_publication_lock "${_dest_dir}"
		return 1
	}

	download_one "${_folder}" stable release "${_adguard_arch}" || true
	download_one "${_folder}" beta beta "${_adguard_arch}" || true
	download_one "${_folder}" edge edge "${_adguard_arch}" || true

	if ! chmod 644 "${_dest_dir}/VERSION.txt.tmp" "${_dest_dir}/checksum.txt.tmp"; then
		rm -f "${_dest_dir}/VERSION.txt.tmp" "${_dest_dir}/checksum.txt.tmp"
		printf '%s\n' "Error: could not set metadata permissions for ${_folder}" >&2
		FAILED=1
		release_metadata_publication_lock "${_dest_dir}"
		return 1
	fi
	if ! publish_metadata_files "${_dest_dir}"; then
		release_metadata_publication_lock "${_dest_dir}"
		return 1
	fi
	if ! prune_stale_versioned_archives "${_dest_dir}" "${_adguard_arch}"; then
		release_metadata_publication_lock "${_dest_dir}"
		return 1
	fi
	release_metadata_publication_lock "${_dest_dir}" || return 1
}

download_one() {
	_folder="$1"
	_channel_name="$2"
	_remote_channel="$3"
	_adguard_arch="$4"
	_adguard_tar="AdGuardHome_${_adguard_arch}.tar.gz"
	_url="${BASE_URL}/${_remote_channel}/${_adguard_tar}"
	_version_url="${BASE_URL}/${_remote_channel}/version.txt"
	_dest_dir="${OUT_DIR}/${_folder}"
	_dest_file="${_dest_dir}/AdGuardHome_${_channel_name}_${_adguard_arch}.tar.gz"
	_dest_name="${_dest_file##*/}"
	_tmp_file="${_dest_file}.tmp.$$"
	_version=""
	_md5=""
	_sha256=""

	printf '%s\n' "Downloading ${_version_url}"
	_version_response="$(curl -fsL --retry 3 --retry-delay 5 --connect-timeout 30 --max-time 120 "${_version_url}")" || {
		printf '%s\n' "Error: failed to download ${_version_url}" >&2
		FAILED=1
		return 1
	}
	_version="$(printf '%s\n' "${_version_response}" | awk 'NF {print $1; found = 1; exit} END {if (!found) exit 1}')" || {
		printf '%s\n' "Error: invalid version metadata from ${_version_url}" >&2
		FAILED=1
		return 1
	}
	if [ -z "${_version}" ]; then
		printf '%s\n' "Error: empty version metadata from ${_version_url}" >&2
		FAILED=1
		return 1
	fi
	case "${_version}" in
		*[!A-Za-z0-9._+=-]*)
			printf '%s\n' "Error: unsafe version metadata from ${_version_url}" >&2
			FAILED=1
			return 1
			;;
	esac
	printf '%s\n' "Downloading ${_url} -> ${_dest_file}"
	ACTIVE_DOWNLOAD_TMP="${_tmp_file}"
	if ! curl -fL --retry 3 --retry-delay 5 --connect-timeout 30 --max-time 600 -o "${_tmp_file}" "${_url}"; then
		cleanup_download_tmp
		printf '%s\n' "Error: failed to download ${_url}" >&2
		FAILED=1
		return 1
	fi

	if ! gzip -t "${_tmp_file}"; then
		cleanup_download_tmp
		printf '%s\n' "Error: downloaded archive is not a valid gzip file: ${_url}" >&2
		FAILED=1
		return 1
	fi

	_md5="$(calc_sum md5sum "${_tmp_file}")" || {
		cleanup_download_tmp
		printf '%s\n' "Error: failed to calculate md5 for ${_url}" >&2
		FAILED=1
		return 1
	}
	_sha256="$(calc_sum sha256sum "${_tmp_file}")" || {
		cleanup_download_tmp
		printf '%s\n' "Error: failed to calculate sha256 for ${_url}" >&2
		FAILED=1
		return 1
	}

	recover_archive_publication "${_dest_file}" || {
		cleanup_download_tmp
		return 1
	}
	if [ -f "${_dest_file}" ] && cmp -s "${_tmp_file}" "${_dest_file}"; then
		printf '%s\n' "OK: ${_dest_file} already current"
		refresh_unchanged_archive_checksums "${_tmp_file}" "${_dest_file}" "${_md5}" "${_sha256}" || {
			cleanup_download_tmp
			return 1
		}
		cleanup_download_tmp
	else
		publish_archive_with_checksums "${_tmp_file}" "${_dest_file}" "${_md5}" "${_sha256}" || {
			ACTIVE_DOWNLOAD_TMP=""
			return 1
		}
		printf '%s\n' "Updated ${_dest_file}"
	fi
	ACTIVE_DOWNLOAD_TMP=""

	if ! append_metadata "${_folder}" "${_channel_name}" "${_remote_channel}" "${_adguard_arch}" "${_dest_name}" "${_version}" "${_md5}" "${_sha256}"; then
		printf '%s\n' "Error: could not append metadata for ${_dest_name}" >&2
		FAILED=1
		return 1
	fi
}

recover_archive_publication() {
	_archive_file="$1"
	_allowed_owner_pid="${2:-}"
	_md5_file="${_archive_file}.md5sum"
	_sha256_file="${_archive_file}.sha256sum"
	_publish_state="${_archive_file}.publish-in-progress"
	_archive_backup="${_archive_file}.previous"
	_md5_backup="${_md5_file}.previous"
	_sha256_backup="${_sha256_file}.previous"
	_archive_restore="${_archive_backup}.restore.$$"
	_md5_restore="${_md5_backup}.restore.$$"
	_sha256_restore="${_sha256_backup}.restore.$$"
	_restore_failed=0
	_publish_phase=""
	_publish_had_archive=""
	_publish_had_md5=""
	_publish_had_sha256=""

	[ -f "${_publish_state}" ] || return 0
	IFS=' ' read -r _publish_pid _publish_start_time _publish_phase \
		_publish_had_archive _publish_had_md5 _publish_had_sha256 <"${_publish_state}" ||
		_publish_phase=""
	_publish_had_sha256="${_publish_had_sha256:-0}"
	if [ "${_publish_pid}" != "${_allowed_owner_pid}" ] &&
		archive_publication_owner_is_active "${_publish_state}"; then
		printf '%s\n' "Error: publication is already in progress for ${_archive_file}" >&2
		FAILED=1
		return 1
	fi

	if [ "${_publish_phase}" != "ready" ] ||
		{ [ "${_publish_had_archive}" = "1" ] && [ ! -f "${_archive_backup}" ]; } ||
		{ [ "${_publish_had_md5}" = "1" ] && [ ! -f "${_md5_backup}" ]; } ||
		{ [ "${_publish_had_sha256}" = "1" ] && [ ! -f "${_sha256_backup}" ]; }; then
		rm -f "${_archive_backup}" "${_md5_backup}" "${_sha256_backup}" "${_publish_state}"
		printf '%s\n' "Discarded incomplete publication preparation for ${_archive_file}" >&2
		return 0
	fi

	rm -f "${_archive_restore}" "${_md5_restore}" "${_sha256_restore}"
	if [ "${_publish_had_archive}" = "1" ]; then
		cp -p "${_archive_backup}" "${_archive_restore}" || _restore_failed=1
	fi
	if [ "${_publish_had_md5}" = "1" ]; then
		cp -p "${_md5_backup}" "${_md5_restore}" || _restore_failed=1
	fi
	if [ "${_publish_had_sha256}" = "1" ]; then
		cp -p "${_sha256_backup}" "${_sha256_restore}" || _restore_failed=1
	fi
	if [ "${_restore_failed}" -ne 0 ]; then
		rm -f "${_archive_restore}" "${_md5_restore}" "${_sha256_restore}"
		printf '%s\n' "Error: could not recover interrupted publication for ${_archive_file}" >&2
		FAILED=1
		return 1
	fi

	if [ "${_publish_had_archive}" = "1" ]; then
		mv "${_archive_restore}" "${_archive_file}" || _restore_failed=1
	else
		rm -f "${_archive_file}" || _restore_failed=1
	fi
	if [ "${_publish_had_md5}" = "1" ]; then
		mv "${_md5_restore}" "${_md5_file}" || _restore_failed=1
	else
		rm -f "${_md5_file}" || _restore_failed=1
	fi
	if [ "${_publish_had_sha256}" = "1" ]; then
		mv "${_sha256_restore}" "${_sha256_file}" || _restore_failed=1
	else
		rm -f "${_sha256_file}" || _restore_failed=1
	fi
	if [ "${_restore_failed}" -ne 0 ]; then
		rm -f "${_archive_restore}" "${_md5_restore}" "${_sha256_restore}"
		printf '%s\n' "Error: could not recover interrupted publication for ${_archive_file}" >&2
		FAILED=1
		return 1
	fi

	rm -f "${_archive_backup}" "${_md5_backup}" "${_sha256_backup}" "${_publish_state}"
	printf '%s\n' "Recovered interrupted publication for ${_archive_file}" >&2
	return 0
}

archive_publication_owner_is_active() {
	_publish_state="$1"
	_publish_pid=""
	_publish_start_time=""
	_publish_details=""
	_current_start_time=""

	IFS=' ' read -r _publish_pid _publish_start_time _publish_details \
		<"${_publish_state}" || return 1
	case "${_publish_pid}:${_publish_start_time}" in
		*[!0-9:]* | *: | :*) return 1 ;;
	esac
	[ "${_publish_pid}" -gt 1 ] || return 1
	kill -0 "${_publish_pid}" 2>/dev/null || return 1
	_current_start_time="$(awk '{
		sub(/^.*\) /, "")
		print $20
	}' "/proc/${_publish_pid}/stat" 2>/dev/null)" || return 1
	case "${_current_start_time}" in
		"" | *[!0-9]*) return 1 ;;
	esac
	[ "${_current_start_time}" = "${_publish_start_time}" ]
}

refresh_unchanged_archive_checksums() {
	_archive_tmp="$1"
	_archive_file="$2"
	_md5="$3"
	_sha256="$4"

	if [ ! -f "${_archive_file}" ] || ! cmp -s "${_archive_tmp}" "${_archive_file}"; then
		printf '%s\n' "Error: ${_archive_file} changed while refreshing its checksums" >&2
		FAILED=1
		return 1
	fi
	if ! write_md5sum_file "${_archive_file}" "${_md5}" ||
		! write_sha256sum_file "${_archive_file}" "${_sha256}"; then
		return 1
	fi
}

refresh_unchanged_archive_md5() {
	_archive_tmp="$1"
	_archive_file="$2"
	_md5="$3"

	if [ ! -f "${_archive_file}" ] || ! cmp -s "${_archive_tmp}" "${_archive_file}"; then
		printf '%s\n' "Error: ${_archive_file} changed while refreshing its checksum" >&2
		FAILED=1
		return 1
	fi
	write_md5sum_file "${_archive_file}" "${_md5}"
}

acquire_archive_publication_state() {
	_publish_state="$1"
	_publish_pid="$2"
	_publish_start_time="$3"
	_publish_phase="${4:-preparing}"

	(
		set -C
		printf '%s %s %s\n' "${_publish_pid}" "${_publish_start_time}" "${_publish_phase}" >"${_publish_state}"
	) 2>/dev/null
}

publish_archive_with_checksums() {
	_archive_tmp="$1"
	_archive_file="$2"
	_md5="$3"
	_sha256="$4"
	_publish_condition="${5:-replace}"
	_md5_file="${_archive_file}.md5sum"
	_sha256_file="${_archive_file}.sha256sum"
	_md5_tmp="${_md5_file}.tmp.$$"
	_sha256_tmp="${_sha256_file}.tmp.$$"
	_publish_state="${_archive_file}.publish-in-progress"
	_publish_state_tmp="${_publish_state}.tmp.$$"
	_archive_backup="${_archive_file}.previous"
	_md5_backup="${_md5_file}.previous"
	_sha256_backup="${_sha256_file}.previous"
	_had_archive=0
	_had_md5=0
	_had_sha256=0
	_publish_start_time=""

	recover_archive_publication "${_archive_file}" || {
		rm -f "${_archive_tmp}"
		return 1
	}
	if ! printf '%s\n' "${_md5}" >"${_md5_tmp}" ||
		! printf '%s\n' "${_sha256}" >"${_sha256_tmp}" ||
		! chmod 644 "${_archive_tmp}" "${_md5_tmp}" "${_sha256_tmp}"; then
		rm -f "${_archive_tmp}" "${_md5_tmp}" "${_sha256_tmp}"
		printf '%s\n' "Error: could not prepare ${_archive_file}" >&2
		FAILED=1
		return 1
	fi

	_publish_start_time="$(awk '{
		sub(/^.*\) /, "")
		print $20
	}' "/proc/$$/stat" 2>/dev/null)" || _publish_start_time=""
	case "${_publish_start_time}" in
		"" | *[!0-9]*)
			rm -f "${_archive_tmp}" "${_md5_tmp}" "${_sha256_tmp}"
			printf '%s\n' "Error: could not identify publication owner for ${_archive_file}" >&2
			FAILED=1
			return 1
			;;
	esac
	if ! acquire_archive_publication_state "${_publish_state}" "$$" "${_publish_start_time}"; then
		rm -f "${_archive_tmp}" "${_md5_tmp}" "${_sha256_tmp}"
		printf '%s\n' "Error: publication is already in progress for ${_archive_file}" >&2
		FAILED=1
		return 1
	fi
	if [ "${_publish_condition}" = "require-unchanged" ] &&
		{ [ ! -f "${_archive_file}" ] || ! cmp -s "${_archive_tmp}" "${_archive_file}"; }; then
		rm -f "${_publish_state}" "${_archive_tmp}" "${_md5_tmp}" "${_sha256_tmp}"
		printf '%s\n' "Error: ${_archive_file} changed while refreshing its checksum" >&2
		FAILED=1
		return 1
	fi

	rm -f "${_archive_backup}" "${_md5_backup}" "${_sha256_backup}"
	if [ -f "${_archive_file}" ]; then
		_had_archive=1
		if ! cp -p "${_archive_file}" "${_archive_backup}"; then
			rm -f "${_publish_state}" "${_archive_tmp}" "${_md5_tmp}" "${_sha256_tmp}"
			printf '%s\n' "Error: could not preserve ${_archive_file}" >&2
			FAILED=1
			return 1
		fi
	fi
	if [ -f "${_md5_file}" ]; then
		_had_md5=1
		if ! cp -p "${_md5_file}" "${_md5_backup}"; then
			rm -f "${_publish_state}" "${_archive_backup}" "${_archive_tmp}" "${_md5_tmp}" "${_sha256_tmp}"
			printf '%s\n' "Error: could not preserve ${_md5_file}" >&2
			FAILED=1
			return 1
		fi
	fi
	if [ -f "${_sha256_file}" ]; then
		_had_sha256=1
		if ! cp -p "${_sha256_file}" "${_sha256_backup}"; then
			rm -f "${_publish_state}" "${_archive_backup}" "${_md5_backup}" \
				"${_archive_tmp}" "${_md5_tmp}" "${_sha256_tmp}"
			printf '%s\n' "Error: could not preserve ${_sha256_file}" >&2
			FAILED=1
			return 1
		fi
	fi
	if ! printf '%s %s ready %s %s %s\n' "$$" "${_publish_start_time}" \
		"${_had_archive}" "${_had_md5}" "${_had_sha256}" >"${_publish_state_tmp}" ||
		! mv "${_publish_state_tmp}" "${_publish_state}"; then
		rm -f "${_publish_state}" "${_archive_backup}" "${_md5_backup}" "${_sha256_backup}" \
			"${_archive_tmp}" "${_md5_tmp}" "${_sha256_tmp}" "${_publish_state_tmp}"
		printf '%s\n' "Error: could not mark rollback copies ready for ${_archive_file}" >&2
		FAILED=1
		return 1
	fi
	ACTIVE_PUBLICATION_ARCHIVE="${_archive_file}"

	# Publish checksums before making a replacement archive visible.  Keep any
	# existing archive in place until the final rename so concurrent readers do
	# not observe a missing public archive during replacement preparation.
	if mv "${_md5_tmp}" "${_md5_file}" &&
		mv "${_sha256_tmp}" "${_sha256_file}" &&
		mv "${_archive_tmp}" "${_archive_file}"; then
		if ! rm -f "${_publish_state}"; then
			ACTIVE_PUBLICATION_ARCHIVE=""
			printf '%s\n' "Error: could not clear publication state for ${_archive_file}" >&2
			FAILED=1
			return 1
		fi
		if ! rm -f "${_archive_backup}" "${_md5_backup}" "${_sha256_backup}"; then
			ACTIVE_PUBLICATION_ARCHIVE=""
			printf '%s\n' "Error: could not remove rollback copies for ${_archive_file}" >&2
			FAILED=1
			return 1
		fi
		ACTIVE_PUBLICATION_ARCHIVE=""
		return 0
	fi

	rm -f "${_archive_tmp}" "${_md5_tmp}" "${_sha256_tmp}"
	printf '%s\n' "Error: could not publish ${_archive_file} and its checksums" >&2
	if ! recover_archive_publication "${_archive_file}" "$$"; then
		printf '%s\n' "Error: recovery failed; inspect ${_archive_backup}, ${_md5_backup}, and ${_sha256_backup}" >&2
	fi
	ACTIVE_PUBLICATION_ARCHIVE=""
	FAILED=1
	return 1
}

publish_archive_with_md5() {
	_archive_tmp="$1"
	_archive_file="$2"
	_md5="$3"
	_publish_condition="${4:-replace}"

	publish_archive_with_checksums "${_archive_tmp}" "${_archive_file}" \
		"${_md5}" "" "${_publish_condition}"
}

prune_stale_versioned_archives() {
	_dest_dir="$1"
	_adguard_arch="$2"
	_checksum_file="${_dest_dir}/checksum.txt"
	_channel_name=""
	_archive_file=""
	_archive_name=""

	[ -f "${_checksum_file}" ] || return 0
	for _channel_name in stable beta edge; do
		for _archive_file in "${_dest_dir}/AdGuardHome_${_channel_name}_"*"_${_adguard_arch}.tar.gz"; do
			[ -e "${_archive_file}" ] || continue
			_archive_name="${_archive_file##*/}"
			if awk -v file="${_archive_name}" '$1 == file { found = 1; exit } END { exit !found }' \
				"${_checksum_file}"; then
				continue
			fi
			if ! rm -f "${_archive_file}" "${_archive_file}.md5sum" "${_archive_file}.sha256sum"; then
				printf '%s\n' "Error: could not prune stale archive ${_archive_file}" >&2
				FAILED=1
				return 1
			fi
		done
	done
}

publish_metadata_files() {
	_dest_dir="$1"
	_version_file="${_dest_dir}/VERSION.txt"
	_checksum_file="${_dest_dir}/checksum.txt"
	_version_tmp="${_version_file}.tmp"
	_checksum_tmp="${_checksum_file}.tmp"
	_publish_state="${_dest_dir}/.metadata.publish-in-progress"
	_publish_state_tmp="${_publish_state}.tmp.$$"
	_version_backup="${_version_file}.previous"
	_checksum_backup="${_checksum_file}.previous"
	_had_version=0
	_had_checksum=0
	_publish_start_time=""

	recover_metadata_publication "${_dest_dir}" || return 1
	_publish_start_time="$(awk '{
		sub(/^.*\) /, "")
		print $20
	}' "/proc/$$/stat" 2>/dev/null)" || _publish_start_time=""
	case "${_publish_start_time}" in
		"" | *[!0-9]*)
			rm -f "${_version_backup}" "${_checksum_backup}"
			printf '%s\n' "Error: could not identify metadata publication owner for ${_dest_dir}" >&2
			FAILED=1
			return 1
			;;
	esac
	if ! acquire_archive_publication_state "${_publish_state}" "$$" \
		"${_publish_start_time}"; then
		printf '%s\n' "Error: metadata publication is already in progress for ${_dest_dir}" >&2
		FAILED=1
		return 1
	fi

	rm -f "${_version_backup}" "${_checksum_backup}"
	if [ -f "${_version_file}" ]; then
		_had_version=1
		if ! cp -p "${_version_file}" "${_version_backup}"; then
			rm -f "${_publish_state}" "${_version_tmp}" "${_checksum_tmp}"
			printf '%s\n' "Error: could not preserve ${_version_file}" >&2
			FAILED=1
			return 1
		fi
	fi
	if [ -f "${_checksum_file}" ]; then
		_had_checksum=1
		if ! cp -p "${_checksum_file}" "${_checksum_backup}"; then
			rm -f "${_publish_state}" "${_version_backup}"
			rm -f "${_version_tmp}" "${_checksum_tmp}"
			printf '%s\n' "Error: could not preserve ${_checksum_file}" >&2
			FAILED=1
			return 1
		fi
	fi
	if ! printf '%s %s ready %s %s\n' "$$" "${_publish_start_time}" \
		"${_had_version}" "${_had_checksum}" >"${_publish_state_tmp}" ||
		! mv "${_publish_state_tmp}" "${_publish_state}"; then
		rm -f "${_publish_state}" "${_version_backup}" "${_checksum_backup}" \
			"${_version_tmp}" "${_checksum_tmp}" "${_publish_state_tmp}"
		printf '%s\n' "Error: could not mark metadata rollback copies ready for ${_dest_dir}" >&2
		FAILED=1
		return 1
	fi

	if mv "${_version_tmp}" "${_version_file}" &&
		mv "${_checksum_tmp}" "${_checksum_file}"; then
		if ! rm -f "${_publish_state}"; then
			printf '%s\n' "Error: could not clear metadata publication state for ${_dest_dir}" >&2
			FAILED=1
			return 1
		fi
		rm -f "${_version_backup}" "${_checksum_backup}"
		return 0
	fi

	rm -f "${_version_tmp}" "${_checksum_tmp}"
	printf '%s\n' "Error: could not publish metadata for ${_dest_dir}" >&2
	if ! recover_metadata_publication "${_dest_dir}" "$$"; then
		printf '%s\n' "Error: metadata recovery failed; inspect ${_version_backup} and ${_checksum_backup}" >&2
	fi
	FAILED=1
	return 1
}

recover_metadata_publication() {
	_dest_dir="$1"
	_allowed_owner_pid="${2:-}"
	_version_file="${_dest_dir}/VERSION.txt"
	_checksum_file="${_dest_dir}/checksum.txt"
	_publish_state="${_dest_dir}/.metadata.publish-in-progress"
	_version_backup="${_version_file}.previous"
	_checksum_backup="${_checksum_file}.previous"
	_version_restore="${_version_backup}.restore.$$"
	_checksum_restore="${_checksum_backup}.restore.$$"
	_restore_failed=0
	_publish_phase=""
	_publish_had_version=""
	_publish_had_checksum=""

	[ -f "${_publish_state}" ] || return 0
	IFS=' ' read -r _publish_pid _publish_start_time _publish_phase \
		_publish_had_version _publish_had_checksum <"${_publish_state}" ||
		_publish_phase=""
	if [ "${_publish_pid}" != "${_allowed_owner_pid}" ] &&
		archive_publication_owner_is_active "${_publish_state}"; then
		printf '%s\n' "Error: metadata publication is already in progress for ${_dest_dir}" >&2
		FAILED=1
		return 1
	fi
	if [ "${_publish_phase}" != "ready" ] ||
		{ [ "${_publish_phase}" = "ready" ] &&
			{ { [ "${_publish_had_version}" = "1" ] && [ ! -f "${_version_backup}" ]; } ||
				{ [ "${_publish_had_checksum}" = "1" ] && [ ! -f "${_checksum_backup}" ]; }; }; }; then
		rm -f "${_version_backup}" "${_checksum_backup}" "${_publish_state}"
		printf '%s\n' "Discarded incomplete metadata publication preparation for ${_dest_dir}" >&2
		return 0
	fi

	rm -f "${_version_restore}" "${_checksum_restore}"
	if [ "${_publish_had_version}" = "1" ]; then
		cp -p "${_version_backup}" "${_version_restore}" || _restore_failed=1
	fi
	if [ "${_publish_had_checksum}" = "1" ]; then
		cp -p "${_checksum_backup}" "${_checksum_restore}" || _restore_failed=1
	fi
	if [ "${_restore_failed}" -ne 0 ]; then
		rm -f "${_version_restore}" "${_checksum_restore}"
		printf '%s\n' "Error: could not recover interrupted metadata publication for ${_dest_dir}" >&2
		FAILED=1
		return 1
	fi

	if [ "${_publish_had_version}" = "1" ]; then
		mv "${_version_restore}" "${_version_file}" || _restore_failed=1
	else
		rm -f "${_version_file}" || _restore_failed=1
	fi
	if [ "${_publish_had_checksum}" = "1" ]; then
		mv "${_checksum_restore}" "${_checksum_file}" || _restore_failed=1
	else
		rm -f "${_checksum_file}" || _restore_failed=1
	fi
	if [ "${_restore_failed}" -ne 0 ]; then
		rm -f "${_version_restore}" "${_checksum_restore}"
		printf '%s\n' "Error: could not recover interrupted metadata publication for ${_dest_dir}" >&2
		FAILED=1
		return 1
	fi

	rm -f "${_version_backup}" "${_checksum_backup}" "${_publish_state}"
	printf '%s\n' "Recovered interrupted metadata publication for ${_dest_dir}" >&2
	return 0
}

release_metadata_publication_lock() {
	_dest_dir="$1"
	_lock_file="${_dest_dir}/.metadata.lock"

	if ! rm -f "${_lock_file}"; then
		printf '%s\n' "Error: could not release metadata publication lock for ${_dest_dir}" >&2
		FAILED=1
		return 1
	fi
}

require_cmd() {
	_cmd="$1"
	if which "${_cmd}" >/dev/null 2>&1; then
		return 0
	fi

	printf '%s\n' "Error: ${_cmd} is required." >&2
	exit 1
}

write_md5sum_file() {
	_archive_file="$1"
	_md5="$2"
	_md5_file="${_archive_file}.md5sum"
	_md5_tmp="${_md5_file}.tmp.$$"

	if ! printf '%s\n' "${_md5}" >"${_md5_tmp}" || ! chmod 644 "${_md5_tmp}" || ! mv "${_md5_tmp}" "${_md5_file}"; then
		rm -f "${_md5_tmp}"
		printf '%s\n' "Error: could not update ${_md5_file}" >&2
		FAILED=1
		return 1
	fi
}

write_sha256sum_file() {
	_archive_file="$1"
	_sha256="$2"
	_sha256_file="${_archive_file}.sha256sum"
	_sha256_tmp="${_sha256_file}.tmp.$$"

	if ! printf '%s\n' "${_sha256}" >"${_sha256_tmp}" || ! chmod 644 "${_sha256_tmp}" || ! mv "${_sha256_tmp}" "${_sha256_file}"; then
		rm -f "${_sha256_tmp}"
		printf '%s\n' "Error: could not update ${_sha256_file}" >&2
		FAILED=1
		return 1
	fi
}

require_cmd awk
require_cmd curl
require_cmd gzip
require_cmd ln
require_cmd md5sum
require_cmd sha256sum

trap cleanup_download_tmp 0
trap 'cleanup_download_tmp; exit 1' HUP INT QUIT ABRT TERM

download_arch armv8 linux_arm64
download_arch armv7 linux_armv7
download_arch armv5 linux_armv5

if [ "${FAILED}" -ne 0 ]; then
	exit 1
fi
